/*
 * build-sample.js — regenerate samples/feature-showcase.doc.
 *
 * A small clean-room showcase of the fidelity JSDoc round-trips, written with the
 * bundled writer (src/textToDoc.js): character extras (superscript / subscript /
 * highlight, alongside bold / italic / colour) and table cell merging + shading.
 * Horizontal merges use Word's native representation — a row with fewer, wider cells
 * (the merged cell spans columns via its rgdxaCenter boundaries).
 *
 *   node scripts/build-sample.js
 */
var fs = require('fs');
var path = require('path');
var textToDoc = require('../src/textToDoc.js');

// COLORREF is 0x00BBGGRR (red is the low byte).
var GREY = 0xC0C0C0, GREEN = 0x00FF00, RED = 0x0000FF, YELLOW = 0x00FFFF, BLUE = 0xFF0000;
var FULL = [0, 3000, 6000, 9000];   // three equal columns
function r3(a, b, c) { return [{ runs: [{ text: a.t || a }], kind: 'cell', shd: a.shd }, { runs: [{ text: b.t || b }], kind: 'cell', shd: b.shd }, { runs: [{ text: c.t || c }], kind: 'rowEnd', shd: c.shd, tblw: FULL }]; }

var model = {
  props: { title: 'JSDoc feature showcase', author: 'Alpaq92', subject: 'Character + table fidelity demo' },
  body: [].concat(
    [{ runs: [{ text: 'JSDoc feature showcase', b: true, size: 15 }], kind: 'p' }],
    [{ runs: [{ text: 'Everything below round-trips through the reader and writer and renders in the demo’s Formatted view.' }], kind: 'p' }],
    // Character extras: superscript / subscript / highlight, alongside bold / italic / colour.
    [{ runs: [
      { text: 'Inline: E = mc' }, { text: '2', va: 'super' }, { text: ', the formula H' }, { text: '2', va: 'sub' },
      { text: 'O, a ' }, { text: 'highlighted', highlight: YELLOW }, { text: ' term and a ' }, { text: 'flagged', highlight: GREEN },
      { text: ' note — plus ' }, { text: 'bold', b: true }, { text: ', ' }, { text: 'italic', i: true },
      { text: ', and ' }, { text: 'blue', color: BLUE }, { text: ' text.' }
    ], kind: 'p' }],
    [{ runs: [{ text: 'A status table with a merged header and shaded cells:', b: true }], kind: 'p' }],
    // Row 1 — header merged across all three columns (one wide cell), grey fill.
    [{ runs: [{ text: 'Project status — Q2', b: true }], kind: 'rowEnd', shd: GREY, tblw: [0, 9000] }],
    // Row 2 — column headings.
    r3({ t: 'Phase' }, { t: 'State' }, { t: 'Owner' }),
    // Rows 3-5 — a shaded State cell per row.
    r3('Design', { t: 'Done', shd: GREEN }, 'Alpaq92'),
    r3('Build', { t: 'Blocked', shd: RED }, 'Alpaq92'),
    r3('Ship', { t: 'Pending', shd: YELLOW }, 'Alpaq92'),
    // Row 6 — "Overall" merged across the first two columns.
    [{ runs: [{ text: 'Overall', b: true }], kind: 'cell' }, { runs: [{ text: 'On track', b: true }], kind: 'rowEnd', tblw: [0, 6000, 9000] }],
    [{ runs: [{ text: 'Generated by scripts/build-sample.js (the bundled writer).' }], kind: 'p' }]
  )
};

var out = path.join(__dirname, '..', 'samples', 'feature-showcase.doc');
fs.writeFileSync(out, Buffer.from(textToDoc(model)));
console.log('wrote ' + out + ' (' + fs.statSync(out).size + ' bytes)');
